# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Money Management' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'

  # Pods for Money Management

  target 'Money ManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Money ManagementUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
